plugins {
    id 'com.android.library'
}

android {
    namespace 'io.github.libxposed.compat'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Добавляем официальную API зависимость, которую Gradle сможет скачать
    compileOnly 'io.github.libxposed:api:3.0.0'
}
